2020-11-16 15:59:26,399   INFO  **********************Start training kitti_models/pv_rcnn_ours_10(default)**********************
Traceback (most recent call last):
  File "train.py", line 204, in <module>?it/s]
    main()
  File "train.py", line 176, in main
    merge_all_iters_to_one_epoch=args.merge_all_iters_to_one_epoch
  File "/team1/codes/3dObjDet/OpenPCDet_ravi/tools/train_utils/train_utils.py", line 100, in train_model
    dataloader_iter=dataloader_iter
  File "/team1/codes/3dObjDet/OpenPCDet_ravi/tools/train_utils/train_utils.py", line 38, in train_one_epoch
    loss, tb_dict, disp_dict = model_func(model, batch)
  File "/team1/codes/3dObjDet/OpenPCDet_ravi/pcdet/models/__init__.py", line 30, in model_func
    ret_dict, tb_dict, disp_dict = model(batch_dict)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/distributed.py", line 376, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/team1/codes/3dObjDet/OpenPCDet_ravi/pcdet/models/detectors/pv_rcnn.py", line 11, in forward
    batch_dict = cur_module(batch_dict)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/team1/codes/3dObjDet/OpenPCDet_ravi/pcdet/models/backbones_3d/spconv_backbone.py", line 139, in forward
    x = self.conv_input(input_sp_tensor)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/spconv/modules.py", line 127, in forward
    input.features = module(input.features)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/batchnorm.py", line 83, in forward
    exponential_average_factor, self.eps)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 1697, in batch_norm
    training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

******************************MORE INFO AFTER DEBUGGING************************
2020-11-16 17:11:31,418   INFO  **********************Start training kitti_models/pv_rcnn_ours_10(default)**********************
epochs:   0%|                                                                                                                                                             | 0/80 [00:00<?, ?it/s]

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.6/multiprocessing/spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "/usr/lib/python3.6/multiprocessing/spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.6/multiprocessing/spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "/usr/lib/python3.6/multiprocessing/spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/launch.py", line 235, in <module>
    main()
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/launch.py", line 231, in main
    cmd=process.args)
subprocess.CalledProcessError: Command '['/usr/local/bin/python', '-u', 'train.py', '--local_rank=0', '--launcher', 'pytorch', '--cfg_file', 'cfgs/kitti_models/pv_rcnn_ours_10.yaml']' died with <Signals.SIGKILL: 9>.
root@team1-vkonduru-ppillarsandpvrcnn-gpu-1:/team1/codes/3dObjDet/OpenPCDet_ravi/tools/scripts# 
root@team1-vkonduru-ppillarsandpvrcnn-gpu-1:/team1/codes/3dObjDet/OpenPCDet_ravi/tools/scripts# 
root@team1-vkonduru-ppillarsandpvrcnn-gpu-1:/team1/codes/3dObjDet/OpenPCDet_ravi/tools/scripts# /usr/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 29 leaked semaphores to clean up at shutdown
  len(cache))
/usr/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 29 leaked semaphores to clean up at shutdown
  len(cache))